// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataBaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models.Configurations
{
    public partial class DepartmentConfiguration : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> entity)
        {
            entity.Property(e => e.Dnum).ValueGeneratedNever();

            entity.HasOne(d => d.MgrssnNavigation).WithMany(p => p.Departments).HasConstraintName("FK_Departments_Employee");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Department> entity);
    }
}
